//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.CropWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://crop-wsn.ddns.net/webservice.asmx/", ConfigurationName="CropWS.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/ValidaUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ValidaUser(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerSectores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LerSectores(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerSectoresMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication3.CropWS.Sectores[] LerSectoresMobile(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerTipoRegisto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LerTipoRegisto(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerTipoRegistoMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication3.CropWS.TipoDeRegisto[] LerTipoRegistoMobile(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerUtilizadores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LerUtilizadores(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerSect_Topog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LerSect_Topog(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerRecolhaValoresMobile_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication3.CropWS.Registos[] LerRecolhaValoresMobile_1(string user, string pass, int id_sector, int id_tp_registo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerRecolhaValoresMobile_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication3.CropWS.Registos[] LerRecolhaValoresMobile_2(string user, string pass, int id_sector, int id_tp_registo, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerRecolhaValoresMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication3.CropWS.Registos[] LerRecolhaValoresMobile(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/RegistarLeituraWSNMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistarLeituraWSNMobile(string user, string pass, string tp_registo, float leitura, int sensor_id, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/RegistarLeituraMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistarLeituraMobile(string user, string pass, string data, int id_Sector, string tp_registo, float leitura, int sensor_id, int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/RegistarLeituraListaMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistarLeituraListaMobile(string user, string pass, WindowsFormsApplication3.CropWS.Registos[] lst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/ApagaRegisto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ApagaRegisto(string user, string pass, string data, int tipo_registo, int id_sector, int id_sensor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crop-wsn.ddns.net/webservice.asmx/LerComentarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LerComentarios(string user, string pass);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crop-wsn.ddns.net/webservice.asmx/")]
    public partial class Sectores : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int id_SectorField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id_Sector {
            get {
                return this.id_SectorField;
            }
            set {
                this.id_SectorField = value;
                this.RaisePropertyChanged("id_Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crop-wsn.ddns.net/webservice.asmx/")]
    public partial class Registos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int puser_idField;
        
        private int psensor_idField;
        
        private string pUsernameField;
        
        private int pParamSqlField;
        
        private int idField;
        
        private string data_leituraField;
        
        private int sectorField;
        
        private int t_regField;
        
        private float registoField;
        
        private int user_idField;
        
        private int sensor_idField;
        
        private string usernameField;
        
        private int paramSqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int puser_id {
            get {
                return this.puser_idField;
            }
            set {
                this.puser_idField = value;
                this.RaisePropertyChanged("puser_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int psensor_id {
            get {
                return this.psensor_idField;
            }
            set {
                this.psensor_idField = value;
                this.RaisePropertyChanged("psensor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pUsername {
            get {
                return this.pUsernameField;
            }
            set {
                this.pUsernameField = value;
                this.RaisePropertyChanged("pUsername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int pParamSql {
            get {
                return this.pParamSqlField;
            }
            set {
                this.pParamSqlField = value;
                this.RaisePropertyChanged("pParamSql");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string data_leitura {
            get {
                return this.data_leituraField;
            }
            set {
                this.data_leituraField = value;
                this.RaisePropertyChanged("data_leitura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int t_reg {
            get {
                return this.t_regField;
            }
            set {
                this.t_regField = value;
                this.RaisePropertyChanged("t_reg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float registo {
            get {
                return this.registoField;
            }
            set {
                this.registoField = value;
                this.RaisePropertyChanged("registo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int sensor_id {
            get {
                return this.sensor_idField;
            }
            set {
                this.sensor_idField = value;
                this.RaisePropertyChanged("sensor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int paramSql {
            get {
                return this.paramSqlField;
            }
            set {
                this.paramSqlField = value;
                this.RaisePropertyChanged("paramSql");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crop-wsn.ddns.net/webservice.asmx/")]
    public partial class TipoDeRegisto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int id_RegistoField;
        
        private string tipoRegistoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id_Registo {
            get {
                return this.id_RegistoField;
            }
            set {
                this.id_RegistoField = value;
                this.RaisePropertyChanged("id_Registo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipoRegisto {
            get {
                return this.tipoRegistoField;
            }
            set {
                this.tipoRegistoField = value;
                this.RaisePropertyChanged("tipoRegisto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication3.CropWS.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication3.CropWS.WebServiceSoap>, WindowsFormsApplication3.CropWS.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ValidaUser(string user, string pass) {
            return base.Channel.ValidaUser(user, pass);
        }
        
        public System.Data.DataTable LerSectores(string user, string pass) {
            return base.Channel.LerSectores(user, pass);
        }
        
        public WindowsFormsApplication3.CropWS.Sectores[] LerSectoresMobile(string user, string pass) {
            return base.Channel.LerSectoresMobile(user, pass);
        }
        
        public System.Data.DataTable LerTipoRegisto(string user, string pass) {
            return base.Channel.LerTipoRegisto(user, pass);
        }
        
        public WindowsFormsApplication3.CropWS.TipoDeRegisto[] LerTipoRegistoMobile(string user, string pass) {
            return base.Channel.LerTipoRegistoMobile(user, pass);
        }
        
        public System.Data.DataTable LerUtilizadores(string user, string pass) {
            return base.Channel.LerUtilizadores(user, pass);
        }
        
        public System.Data.DataTable LerSect_Topog(string user, string pass) {
            return base.Channel.LerSect_Topog(user, pass);
        }
        
        public WindowsFormsApplication3.CropWS.Registos[] LerRecolhaValoresMobile_1(string user, string pass, int id_sector, int id_tp_registo) {
            return base.Channel.LerRecolhaValoresMobile_1(user, pass, id_sector, id_tp_registo);
        }
        
        public WindowsFormsApplication3.CropWS.Registos[] LerRecolhaValoresMobile_2(string user, string pass, int id_sector, int id_tp_registo, string data) {
            return base.Channel.LerRecolhaValoresMobile_2(user, pass, id_sector, id_tp_registo, data);
        }
        
        public WindowsFormsApplication3.CropWS.Registos[] LerRecolhaValoresMobile(string user, string pass) {
            return base.Channel.LerRecolhaValoresMobile(user, pass);
        }
        
        public int RegistarLeituraWSNMobile(string user, string pass, string tp_registo, float leitura, int sensor_id, string comentario) {
            return base.Channel.RegistarLeituraWSNMobile(user, pass, tp_registo, leitura, sensor_id, comentario);
        }
        
        public int RegistarLeituraMobile(string user, string pass, string data, int id_Sector, string tp_registo, float leitura, int sensor_id, int user_id) {
            return base.Channel.RegistarLeituraMobile(user, pass, data, id_Sector, tp_registo, leitura, sensor_id, user_id);
        }
        
        public int RegistarLeituraListaMobile(string user, string pass, WindowsFormsApplication3.CropWS.Registos[] lst) {
            return base.Channel.RegistarLeituraListaMobile(user, pass, lst);
        }
        
        public int ApagaRegisto(string user, string pass, string data, int tipo_registo, int id_sector, int id_sensor) {
            return base.Channel.ApagaRegisto(user, pass, data, tipo_registo, id_sector, id_sensor);
        }
        
        public System.Data.DataTable LerComentarios(string user, string pass) {
            return base.Channel.LerComentarios(user, pass);
        }
    }
}
